[tox]
envlist = cover, black, flake8, pylint
requires = tox-uv>=1
isolated_build = false
skipsdist = true

[testenv]
deps = -rrequirements-dev.txt

[testenv:cover]
deps =
    {[testenv]deps}
    coverage
commands =
    coverage run -m pytest tests/
    coverage report -m
    coverage html

[testenv:black]
deps = black
skip_install = true
commands = black --check --diff src/ tests/

[testenv:autoformat]
deps = black
skip_install = true
commands = black src/ tests/

[testenv:isort]
deps = isort
skip_install = true
commands = isort --check-only src/ tests/

[testenv:flake8]
deps = flake8
skip_install = true
commands = flake8 --max-line-length=80 --max-complexity=10 --extend-ignore=E203 src/

[testenv:pylint]
deps =
    pylint
    -rrequirements.txt
commands = pylint src/
